#include "pch.h"
#include "Utility.h"


namespace topo
{
PRIMITIVE_TOPOLOGY_TYPE DeducePrimitiveTopologyType(PRIMITIVE_TOPOLOGY topology)
{
	switch (topology)
	{
        case PRIMITIVE_TOPOLOGY::UNDEFINED: return PRIMITIVE_TOPOLOGY_TYPE::UNDEFINED;

        case PRIMITIVE_TOPOLOGY::POINTLIST: return PRIMITIVE_TOPOLOGY_TYPE::POINT;

        case PRIMITIVE_TOPOLOGY::LINELIST:
        case PRIMITIVE_TOPOLOGY::LINESTRIP:
        case PRIMITIVE_TOPOLOGY::LINELIST_ADJ:
        case PRIMITIVE_TOPOLOGY::LINESTRIP_ADJ: return PRIMITIVE_TOPOLOGY_TYPE::LINE;

        case PRIMITIVE_TOPOLOGY::TRIANGLELIST:
        case PRIMITIVE_TOPOLOGY::TRIANGLESTRIP:
        case PRIMITIVE_TOPOLOGY::TRIANGLELIST_ADJ:
        case PRIMITIVE_TOPOLOGY::TRIANGLESTRIP_ADJ: return PRIMITIVE_TOPOLOGY_TYPE::TRIANGLE;

        case PRIMITIVE_TOPOLOGY::TOPOLOGY_1_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_2_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_3_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_4_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_5_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_6_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_7_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_8_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_9_CONTROL_POINT_PATCHLIST: 
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_10_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_11_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_12_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_13_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_14_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_15_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_16_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_17_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_18_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_19_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_20_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_21_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_22_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_23_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_24_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_25_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_26_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_27_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_28_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_29_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_30_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_31_CONTROL_POINT_PATCHLIST:
        case PRIMITIVE_TOPOLOGY::TOPOLOGY_32_CONTROL_POINT_PATCHLIST: return PRIMITIVE_TOPOLOGY_TYPE::PATCH;
	}

	return PRIMITIVE_TOPOLOGY_TYPE::UNDEFINED;
}
}